In [5]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
%store -r subjects
%store -r eeg_final
%store -r stimulus
%store -r master_df
%store -r master_time
%store -r master_label_df


In [7]:
master_label_df

Unnamed: 0  id              indra_time browser_latency  \
677         27618   8 2015-05-09 23:32:41.663             -38   
678         27619   8 2015-05-09 23:32:42.571             -39   
679         27620   8 2015-05-09 23:32:43.481             -39   
680         27621   8 2015-05-09 23:32:44.698             -39   
681         27622   8 2015-05-09 23:32:45.609             -39   
...           ...  ..                     ...             ...   
26443       18015  27 2015-05-09 23:48:48.296            -938   
26444       18016  27 2015-05-09 23:48:49.516            -939   
26445       18017  27 2015-05-09 23:48:50.433            -939   
26446       18018  27 2015-05-09 23:48:51.346            -939   
26447       18019  27 2015-05-09 23:48:52.567            -938   

                 reading_time  attention_esense  meditation_esense  \
677   2015-05-09 16:32:41.788                64                 67   
678   2015-05-09 16:32:42.789                80                 83   
679   2015-05-09 16:32:43.755                90                 90   
680   2015-05-09 16:32:44.758                93                 83   
681   2015-05-09 16:32:45.742                91                 90   
...                       ...               ...                ...   
26443 2015-05-09 16:48:49.516                84                 29   
26444 2015-05-09 16:48:50.536                74                 20   
26445 2015-05-09 16:48:51.534                67                 23   
26446 2015-05-09 16:48:52.522                66                 24   
26447 2015-05-09 16:48:53.527                44                 43   

                                               eeg_power  \
677    [741016.0, 1068203.0, 253428.0, 112710.0, 1715...   
678    [9416.0, 13022.0, 18955.0, 15597.0, 8903.0, 20...   
679    [116550.0, 7062.0, 10241.0, 2245.0, 4162.0, 65...   
680    [13884.0, 5769.0, 8625.0, 1837.0, 6221.0, 2283...   
681    [701748.0, 51032.0, 24760.0, 6768.0, 3128.0, 8...   
...                                                  ...   
26443  [34004.0, 9627.0, 3836.0, 9513.0, 8240.0, 8078...   
26444  [1602302.0, 202666.0, 40488.0, 38347.0, 5081.0...   
26445  [634272.0, 336226.0, 67494.0, 17244.0, 8897.0,...   
26446  [109181.0, 46985.0, 15022.0, 17584.0, 15259.0,...   
26447  [1357718.0, 8132.0, 5568.0, 5254.0, 2544.0, 46...   

                                              raw_values  signal_quality  ...  \
677    [49.0, 61.0, 92.0, 91.0, 56.0, 25.0, 25.0, 53....               0  ...   
678    [27.0, 39.0, 65.0, 92.0, 103.0, 84.0, 70.0, 75...               0  ...   
679    [58.0, 17.0, 3.0, 39.0, 96.0, 117.0, 99.0, 73....               0  ...   
680    [124.0, 101.0, 67.0, 75.0, 106.0, 99.0, 66.0, ...               0  ...   
681    [132.0, 141.0, 154.0, 155.0, 137.0, 104.0, 80....               0  ...   
...                                                  ...             ...  ...   
26443  [39.0, 52.0, 44.0, 44.0, 59.0, 55.0, 35.0, 21....               0  ...   
26444  [117.0, 118.0, 67.0, 25.0, -5.0, -29.0, -39.0,...               0  ...   
26445  [67.0, 40.0, -4.0, -24.0, 5.0, 67.0, 106.0, 92...               0  ...   
26446  [684.0, 620.0, 565.0, 552.0, 541.0, 553.0, 577...               0  ...   
26447  [3.0, 23.0, 19.0, -1.0, 8.0, 48.0, 64.0, 42.0,...               0  ...   

       low_beta high_beta low_gamma  mid+gamma  Session  Seen video before?  \
677    171571.0  138093.0   19539.0    13687.0        1                   n   
678      8903.0   20473.0    5763.0     7271.0        1                   n   
679      4162.0    6597.0    1435.0     4858.0        1                   n   
680      6221.0   22838.0   11360.0    13625.0        1                   n   
681      3128.0    8376.0    4160.0     3705.0        1                   n   
...         ...       ...       ...        ...      ...                 ...   
26443    8240.0   80781.0   39374.0    16310.0        2                   y   
26444    5081.0   26990.0   21178.0    15716.0        2    

In [8]:
from sklearn.model_selection import train_test_split, KFold, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.svm import SVC

In [9]:
# svm = SVC(kernel='linear', C=1, random_state = 101)
# for i in range(1,31):
#     subject = master_time[master_time['id'] == i]
#     features = subject.drop(['id', 'label'], axis = 1)
#     scores = cross_val_score(svm, features, subject['label'], 
#                              cv = 5, scoring = 'accuracy')  
#     mean_score = scores.mean()
#     print(f'Subject {i} Results with CV accuracy of {mean_score} \n')
#     print(scores)
#     print(mean_score)
#     accuracy_list.append(mean_score)

In [10]:
# svm = SVC(kernel='linear', C=1, random_state = 101)
# subject = master_time[master_time['id'] == 1]
# features = subject.drop(['id', 'label'], axis = 1)
# scores = cross_val_score(svm, features, subject['label'], 
#                              cv = 5, scoring = 'accuracy')  
# mean_score = scores.mean()
# print(f'Subject {i} Results with CV accuracy of {mean_score} \n')
# print(scores)
# print(mean_score)

In [11]:
math_relax = master_label_df[master_label_df.label.isin(['math','relax'])] 

In [12]:
math_relax.label.unique()

array(['relax', 'math'], dtype=object)

In [13]:
math_relax['label'].value_counts()

math     936
relax    934
Name: label, dtype: int64

In [14]:
subject = math_relax[math_relax['id'] == 1]
subject

Unnamed: 0  id              indra_time browser_latency  \
16409         537   1 2015-05-09 23:32:54.153           13404   
16410         538   1 2015-05-09 23:32:55.061           13404   
16411         539   1 2015-05-09 23:32:55.971           13404   
16412         536   1 2015-05-09 23:32:57.179           13404   
16413         540   1 2015-05-09 23:32:58.089           13404   
16414         541   1 2015-05-09 23:32:58.999           13404   
16415         543   1 2015-05-09 23:33:00.211           13404   
16416         542   1 2015-05-09 23:33:01.121           13405   
16417         544   1 2015-05-09 23:33:02.031           13405   
16418         545   1 2015-05-09 23:33:02.940           13405   
16419         546   1 2015-05-09 23:33:04.144           13404   
16420         547   1 2015-05-09 23:33:05.048           13404   
16421         548   1 2015-05-09 23:33:05.956           13404   
16422         549   1 2015-05-09 23:33:07.171           13404   
16423         550   1 2015-05-09 23:33:08.082           13404   
16424         551   1 2015-05-09 23:33:08.992           13404   
16425         552   1 2015-05-09 23:33:10.204           13404   
16426         553   1 2015-05-09 23:33:11.112           13404   
16427         554   1 2015-05-09 23:33:12.021           13404   
16428         555   1 2015-05-09 23:33:12.928           13403   
16429         556   1 2015-05-09 23:33:14.139           13403   
16430         557   1 2015-05-09 23:33:15.047           13403   
16431         558   1 2015-05-09 23:33:15.954           13403   
16432         559   1 2015-05-09 23:33:17.166           13403   
16433         560   1 2015-05-09 23:33:18.073           13403   
16434         561   1 2015-05-09 23:33:18.981           13403   
16435         562   1 2015-05-09 23:33:19.889           13403   
16436         563   1 2015-05-09 23:33:21.100           13403   
16437         564   1 2015-05-09 23:33:22.007           13403   
16438         565   1 2015-05-09 23:33:22.916           13403   
16444         571   1 2015-05-09 23:33:28.977           13403   
16445         572   1 2015-05-09 23:33:29.889           13403   
16446         573   1 2015-05-09 23:33:31.107           13405   
16447         574   1 2015-05-09 23:33:32.019           13405   
16448         575   1 2015-05-09 23:33:32.923           13405   
16449         576   1 2015-05-09 23:33:34.128           13402   
16450         577   1 2015-05-09 23:33:35.037           13402   
16451         578   1 2015-05-09 23:33:35.950           13402   
16452         579   1 2015-05-09 23:33:36.857           13402   
16453         580   1 2015-05-09 23:33:38.069           13402   
16454         581   1 2015-05-09 23:33:38.981           13402   
16455         582   1 2015-05-09 23:33:39.886           13402   
16456         583   1 2015-05-09 23:33:40.795           13402   
16457         584   1 2015-05-09 23:33:42.005           13402   
16458         585   1 2015-05-09 23:33:42.915           13402   
16459         586   1 2015-05-09 23:33:43.823           13402   
16460         587   1 2015-05-09 23:33:45.035           13402   
16461         588   1 2015-05-09 23:33:45.938           13401   
16462         589   1 2015-05-09 23:33:46.846           13401   
16463         590   1 2015-05-09 23:33:48.059           13401   
16464         591   1 2015-05-09 23:33:48.970           13401   
16465         592   1 2015-05-09 23:33:49.879           13401   
16466         593   1 2015-05-09 23:33:50.792           13401   
16467         594   1 2015-05-09 23:33:52.005           13401   
16468         595   1 2015-05-09 23:33:52.916           13401   
16469         596   1 2015-05-09 23:33:53.831           13401   
16470         598   1 2015-05-09 23:33:54.742           13401   
16471         599   1 2015-05-09 23:33:55.956           13401   
16472         600   1 2015-05-09 23:33:56.866           13401   
16473         601   1 2015-05-09 23:33:57.774           13400   

                 reading_time  attention_

In [15]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import roc_curve, auc, cross_validate

In [16]:
features = math_relax.drop(['Unnamed: 0', 'id', 'indra_time','reading_time', 'browser_latency', 'eeg_power', 'raw_values',
       'signal_quality', 'createdAt', 'updatedAt', 'Session', 'Seen video before?', 'Chosen color',
       'Saw icons?', 'Gender', 'Wear contacts','label'], axis = 1)
X_train, X_test, y_train, y_test = train_test_split(features,math_relax['label'], test_size=0.30)

In [17]:
knn = KNeighborsClassifier(n_neighbors = 6)
knn.fit(X_train,y_train)
pred = knn.predict(X_test)
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

        math       0.55      0.70      0.62       277
       relax       0.60      0.44      0.51       284

    accuracy                           0.57       561
   macro avg       0.58      0.57      0.56       561
weighted avg       0.58      0.57      0.56       561



In [18]:
#calculate accuracy/precision/recall/f1

# accuracy: (tp + tn) / (p + n)
accuracy = (accuracy_score(y_test, pred)).astype('float64')
print('{:>10}: {:0.2%}'.format('Accuracy',accuracy))
# precision tp / (tp + fp)
precision = (precision_score(y_test, pred, average = 'weighted')).astype('float64')
print('{:>10}: {:0.2%}'.format('Precision',precision))
# recall: tp / (tp + fn)
recall = (recall_score(y_test, pred, average = 'weighted')).astype('float64')
print('{:>10}: {:0.2%}'.format('Recall',recall))
# f1: 2 tp / (2 tp + fp + fn)
f1 = (f1_score(y_test, pred, average = 'weighted')).astype('float64')
print('{:>10}: {:0.2%}'.format('F1 score',f1))

# #ROC curve
# false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, pred)
# roc_auc = (auc(false_positive_rate, true_positive_rate)).astype('float64')
# print('{:>10}: {:0.2%}'.format('ROC score',roc_auc))

  Accuracy: 56.86%
 Precision: 57.56%
    Recall: 56.86%
  F1 score: 56.13%


In [20]:
accText = 'KNN, Math vs Relax'
acc = pd.read_csv("accuracies.csv", index_col=0)
acc.at[accText, 'Accuracy'] = (accuracy)
acc.at[accText, 'Precision'] = (precision)
acc.at[accText, 'Recall'] = (recall)
acc.at[accText, 'F1'] = (f1)
# acc.at[accText, 'ROC'] = (roc_auc)
acc.to_csv("accuracies.csv")

###### It's a little better than random...

# Per Subject Tests

In [75]:
math_relax_trim = math_relax.drop(['Unnamed: 0', 'indra_time','reading_time', 'browser_latency', 'eeg_power', 'raw_values',
       'signal_quality', 'createdAt', 'updatedAt', 'Session', 'Seen video before?', 'Chosen color',
       'Saw icons?', 'Gender', 'Wear contacts','attention_esense','meditation_esense'], axis = 1)
math_relax_trim.loc[math_relax_trim.label == 'relax','label'] = 0
math_relax_trim.loc[math_relax_trim.label == 'math','label'] = 1
math_relax_trim['label'] = math_relax_trim.label.astype(int)
math_relax_trim


id  label      delta     theta  low_alpha  high_alpha  low_beta  \
690     8      0  1158761.0  122862.0    31168.0     68083.0   46057.0   
691     8      0   389639.0   48498.0    13741.0     10362.0   12736.0   
692     8      0   710350.0   60130.0    11277.0     16637.0   41050.0   
693     8      0   342096.0   13945.0     9479.0      3609.0    4962.0   
694     8      0   377172.0   77455.0    63315.0      6237.0    4283.0   
...    ..    ...        ...       ...        ...         ...       ...   
26207  27      1    16168.0    4363.0      669.0      9654.0    6726.0   
26208  27      1    37818.0   11935.0      996.0     13823.0   29309.0   
26209  27      1   264800.0   89151.0    13650.0      4509.0    8963.0   
26210  27      1     3530.0    6675.0     7446.0      3403.0    4497.0   
26211  27      1   577033.0   21286.0    11050.0      6076.0   10917.0   

       high_beta  low_gamma  mid+gamma  
690      15456.0     9768.0     3260.0  
691      15956.0     3565.0     3610.0  
692      34083.0    19829.0    18299.0  
693       2477.0     1346.0      474.0  
694      16340.0     6204.0     1290.0  
...          ...        ...        ...  
26207    62302.0    79924.0     8924.0  
26208    63970.0    32055.0    19320.0  
26209    21334.0    20599.0     8955.0  
26210    68995.0    30822.0    10568.0  
26211    49800.0    44177.0     9853.0  

[1870 rows x 10 columns]

In [67]:
knn = KNeighborsClassifier(n_neighbors=5)
accuracy_list = []
recall_list = []
precision_list = []
f1_list = [] 


for i in range(1,31):
    subject = math_relax_trim[math_relax_trim['id'] == i]
    features = subject.drop(['id', 'label'], axis = 1)
    accuracy_all = cross_val_score(knn, features, subject['label'], 
                             cv = 5, scoring = 'accuracy')
    precision_all = cross_val_score(knn, features, subject['label'], 
                             cv = 5, scoring = 'precision') 
    recall_all = cross_val_score(knn, features, subject['label'], 
                             cv = 5, scoring = 'recall')
    f1_all= cross_val_score(knn, features, subject['label'], 
                             cv = 5, scoring = 'f1')
    accuracy_list.append(accuracy_all.mean())
    precision_list.append(precision_all.mean())
    recall_list.append(recall_all.mean())
    f1_list.append(f1_all.mean())
    print(f'Subject {i} Results with CV accuracy of {accuracy_all.mean()} \n')
    print(accuracy_all)
    print(recall_all)
    print(precision_all)
    print(f1_all)

Subject 1 Results with CV accuracy of 0.8666666666666666 

[1.         0.75       1.         0.91666667 0.66666667]
[1.         1.         1.         0.83333333 0.5       ]
[1.         0.66666667 1.         1.         0.75      ]
[1.         0.8        1.         0.90909091 0.6       ]
Subject 2 Results with CV accuracy of 0.4935897435897436 

[0.38461538 0.5        0.41666667 0.5        0.66666667]
[0.42857143 0.33333333 0.5        0.5        0.66666667]
[0.42857143 0.5        0.42857143 0.5        0.66666667]
[0.42857143 0.4        0.46153846 0.5        0.66666667]
Subject 3 Results with CV accuracy of 0.8621212121212121 

[0.83333333 1.         0.91666667 0.83333333 0.72727273]
[0.83333333 1.         1.         1.         0.66666667]
[0.83333333 1.         0.875      0.77777778 0.8       ]
[0.83333333 1.         0.93333333 0.875      0.72727273]
Subject 4 Results with CV accuracy of 0.5948717948717948 

[0.69230769 0.61538462 0.75       0.5        0.41666667]
[0.83333333 0.57142857 

In [68]:
accuracy = sum(accuracy_list)/len(accuracy_list)
precision = sum(precision_list)/len(precision_list)
recall = sum(recall_list)/len(recall_list)
f1 = sum(f1_list)/len(f1_list)

In [69]:
print(f'accuracy is {accuracy}')
print(f'precision is {precision}')
print(f'recall is {recall}')
print(f'd1_score is {f1}')

accuracy is 0.6382867132867133
precision is 0.6512881192881196
recall is 0.6697777777777776
d1_score is 0.642859588124294


In [70]:
accText = 'KNN, Math vs Relax, per Subject Cross Validation'

acc = pd.read_csv("accuracies.csv", index_col=0)
acc.at[accText, 'Accuracy'] = (accuracy)
acc.at[accText, 'Precision'] = (precision)
acc.at[accText, 'Recall'] = (recall)
acc.at[accText, 'F1'] = (f1)
# acc.at[accText, 'ROC'] = (roc_auc)
acc.to_csv("accuracies.csv")

In [20]:
features

attention_esense  meditation_esense      delta     theta  low_alpha  \
690                  27                 64  1158761.0  122862.0    31168.0   
691                  34                 64   389639.0   48498.0    13741.0   
692                  34                 64   710350.0   60130.0    11277.0   
693                  34                 64   342096.0   13945.0     9479.0   
694                  38                 78   377172.0   77455.0    63315.0   
...                 ...                ...        ...       ...        ...   
26207               100                 20    16168.0    4363.0      669.0   
26208               100                 11    37818.0   11935.0      996.0   
26209               100                 10   264800.0   89151.0    13650.0   
26210               100                  8     3530.0    6675.0     7446.0   
26211                94                 11   577033.0   21286.0    11050.0   

       high_alpha  low_beta  high_beta  low_gamma  mid+gamma  
690       68083.0   46057.0    15456.0     9768.0     3260.0  
691       10362.0   12736.0    15956.0     3565.0     3610.0  
692       16637.0   41050.0    34083.0    19829.0    18299.0  
693        3609.0    4962.0     2477.0     1346.0      474.0  
694        6237.0    4283.0    16340.0     6204.0     1290.0  
...           ...       ...        ...        ...        ...  
26207      9654.0    6726.0    62302.0    79924.0     8924.0  
26208     13823.0   29309.0    63970.0    32055.0    19320.0  
26209      4509.0    8963.0    21334.0    20599.0     8955.0  
26210      3403.0    4497.0    68995.0    30822.0    10568.0  
26211      6076.0   10917.0    49800.0    44177.0     9853.0  

[1870 rows x 10 columns]

In [10]:
def cross_val_svm (X,y,n):
    clf = svm.SVC()
    scores = cross_val_score(clf, X, y, cv=n)
    return scores  

In [11]:
X, y = 
cross_val_svm(X,y,7)

NameError: name 'vectors_labels' is not defined

# LogisticRegression

In [109]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler, LabelBinarizer
scaler = StandardScaler()

In [110]:
features = math_relax.drop(['Unnamed: 0', 'id', 'indra_time','reading_time', 'browser_latency', 'eeg_power', 'raw_values',
       'signal_quality', 'createdAt', 'updatedAt', 'Session', 'Seen video before?', 'Chosen color',
       'Saw icons?', 'Gender', 'Wear contacts','label'], axis = 1)
scaled_data = scaler.fit_transform(features)
X_train, X_test, y_train, y_test = train_test_split(features,math_relax['label'], test_size=0.30)


In [111]:
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)

C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [112]:
pred = logmodel.predict(X_test)

In [113]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

        math       0.53      0.63      0.57       262
       relax       0.61      0.50      0.55       299

    accuracy                           0.56       561
   macro avg       0.57      0.57      0.56       561
weighted avg       0.57      0.56      0.56       561



In [114]:
#calculate accuracy/precision/recall/f1

# accuracy: (tp + tn) / (p + n)
accuracy = (accuracy_score(y_test, pred)).astype('float64')
print('{:>10}: {:0.2%}'.format('Accuracy',accuracy))
# precision tp / (tp + fp)
precision = (precision_score(y_test, pred, pos_label = 'math' )).astype('float64')
print('{:>10}: {:0.2%}'.format('Precision',precision))
# recall: tp / (tp + fn)
recall = (recall_score(y_test, pred, pos_label = 'math' )).astype('float64')
print('{:>10}: {:0.2%}'.format('Recall',recall))
# f1: 2 tp / (2 tp + fp + fn)
f1 = (f1_score(y_test, pred, pos_label = 'math' )).astype('float64')
print('{:>10}: {:0.2%}'.format('F1 score',f1))

#ROC curve
# false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, pred, pos_label = 'math' )
# roc_auc = (auc(false_positive_rate, true_positive_rate)).astype('float64')
# print('{:>10}: {:0.2%}'.format('ROC score',roc_auc))

  Accuracy: 56.15%
 Precision: 52.55%
    Recall: 62.98%
  F1 score: 57.29%


In [115]:
accText = 'Logistic Regression'
acc = pd.read_csv("accuracies.csv", index_col=0)
acc.at[accText, 'Accuracy'] = (accuracy)
acc.at[accText, 'Precision'] = (precision)
acc.at[accText, 'Recall'] = (recall)
acc.at[accText, 'F1'] = (f1)
# acc.at[accText, 'ROC'] = (roc_auc)
acc.to_csv("accuracies.csv")

Around the same percentages reached with Logistic Regression

# Logistic Regression CrossValidation

In [98]:
scores = cross_val_score(logmodel, scaled_data, math_relax['label'], 
                             cv = 10, scoring = 'accuracy')  
accuracy = scores.mean()
accuracy

0.5978609625668448

In [105]:
precision_scores = cross_val_score(logmodel, scaled_data, math_relax_trim['label'], 
                             cv = 10, scoring = 'precision') 
precision = precision_scores.mean()
precision

0.6073667864560359

In [106]:
recall_scores = cross_val_score(logmodel, scaled_data, math_relax_trim['label'], 
                             cv = 10, scoring = 'recall') 
recall = recall_scores.mean()
recall

0.5929764355982613

In [107]:
f1_scores = cross_val_score(logmodel, scaled_data, math_relax_trim['label'], 
                             cv = 10, scoring = 'f1') 
f1 = f1_scores.mean()
f1

0.5846171859089114

In [108]:
accText = 'Logistic Regression, Cross Validated'
acc = pd.read_csv("accuracies.csv", index_col=0)
acc.at[accText, 'Accuracy'] = (accuracy)
acc.at[accText, 'Precision'] = (precision)
acc.at[accText, 'Recall'] = (recall)
acc.at[accText, 'F1'] = (f1)
# acc.at[accText, 'ROC'] = (roc_auc)
acc.to_csv("accuracies.csv")

# Logistic Regression Per Subject

In [116]:
logmodel = LogisticRegression()
accuracy_list = []
recall_list = []
precision_list = []
f1_list = [] 

for i in range(1,31):
    subject = math_relax_trim[math_relax_trim['id'] == i]
    features = subject.drop(['label'], axis = 1)
    scaled_data = scaler.fit_transform(features)
    accuracy_all = cross_val_score(logmodel, features, subject['label'], 
                             cv = 5, scoring = 'accuracy')
    precision_all = cross_val_score(logmodel, features, subject['label'], 
                             cv = 5, scoring = 'precision') 
    recall_all = cross_val_score(logmodel, features, subject['label'], 
                             cv = 5, scoring = 'recall')
    f1_all= cross_val_score(logmodel, features, subject['label'], 
                             cv = 5, scoring = 'f1')
    accuracy_list.append(accuracy_all.mean())
    precision_list.append(precision_all.mean())
    recall_list.append(recall_all.mean())
    f1_list.append(f1_all.mean())
    print(f'Subject {i} Results with CV accuracy of {accuracy_all.mean()} \n')
    print(accuracy_all)
    print(recall_all)
    print(precision_all)
    print(f1_all)

C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 1 Results with CV accuracy of 0.8833333333333332 

[0.83333333 1.         0.91666667 0.91666667 0.75      ]
[0.83333333 1.         1.         0.83333333 0.5       ]
[0.83333333 1.         0.85714286 1.         1.        ]
[0.83333333 1.         0.92307692 0.90909091 0.66666667]
Subject 2 Results with CV accuracy of 0.5294871794871795 

[0.23076923 0.58333333 0.75       0.33333333 0.75      ]
[0.28571429 0.33333333 1.         0.16666667 0.66666667]
[0.28571429 0.66666667 0.66666667 0.25       0.8       ]
[0.28571429 0.44444444 0.8        0.2        0.72727273]
Subject 3 Results with CV accuracy of 0.8621212121212121 

[0.91666667 1.         0.83333333 0.83333333 0.72727273]
[0.83333333 1.         1.         1.         0.66666667]
[1.         1.         0.77777778 0.77777778 0.8       ]
[0.90909091 1.         0.875      0.875      0.72727273]
Subject 4 Results with CV accuracy of 0.3833333333333333 

[0.46153846 0.53846154 0.5        0.33333333 0.08333333]
[0.16666667 0.42857143 

C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 5 Results with CV accuracy of 0.7410256410256411 

[0.53846154 0.66666667 1.         0.83333333 0.66666667]
[1.         1.         1.         0.66666667 0.33333333]
[0.5 0.6 1.  1.  1. ]
[0.66666667 0.75       1.         0.8        0.5       ]
Subject 6 Results with CV accuracy of 0.5833333333333333 

[0.58333333 0.83333333 0.41666667 0.41666667 0.66666667]
[0.5        0.83333333 0.5        0.16666667 0.5       ]
[0.6        0.83333333 0.42857143 0.33333333 0.75      ]
[0.54545455 0.83333333 0.46153846 0.22222222 0.6       ]


C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 7 Results with CV accuracy of 0.7038461538461538 

[0.76923077 0.5        0.58333333 0.75       0.91666667]
[0.83333333 0.83333333 0.16666667 0.66666667 0.83333333]
[0.71428571 0.5        1.         0.8        1.        ]
[0.76923077 0.625      0.28571429 0.72727273 0.90909091]


C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 8 Results with CV accuracy of 0.6500000000000001 

[0.41666667 0.75       0.75       0.75       0.58333333]
[0.5        0.83333333 0.66666667 0.66666667 0.33333333]
[0.42857143 0.71428571 0.8        0.8        0.66666667]
[0.46153846 0.76923077 0.72727273 0.72727273 0.44444444]


C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 9 Results with CV accuracy of 0.6666666666666666 

[0.66666667 0.66666667 0.58333333 0.75       0.66666667]
[0.5        0.66666667 0.5        0.83333333 0.66666667]
[0.75       0.66666667 0.6        0.71428571 0.66666667]
[0.6        0.66666667 0.54545455 0.76923077 0.66666667]


C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 10 Results with CV accuracy of 0.6333333333333333 

[0.16666667 0.75       0.5        0.75       1.        ]
[0.         0.5        0.83333333 0.83333333 1.        ]
[0.         1.         0.5        0.71428571 1.        ]
[0.         0.66666667 0.625      0.76923077 1.        ]


C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 11 Results with CV accuracy of 0.7269230769230768 

[0.38461538 0.75       0.91666667 0.91666667 0.66666667]
[0.5        0.66666667 0.83333333 0.83333333 0.66666667]
[0.375      0.8        1.         1.         0.66666667]
[0.42857143 0.72727273 0.90909091 0.90909091 0.66666667]


C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 12 Results with CV accuracy of 0.6333333333333334 

[0.41666667 0.83333333 0.75       0.58333333 0.58333333]
[0.66666667 0.66666667 0.5        0.5        0.66666667]
[0.44444444 1.         1.         0.6        0.57142857]
[0.53333333 0.8        0.66666667 0.54545455 0.61538462]
Subject 13 Results with CV accuracy of 0.8833333333333332 

[0.58333333 1.         0.91666667 0.91666667 1.        ]
[0.83333333 1.         0.83333333 0.83333333 1.        ]
[0.55555556 1.         1.         1.         1.        ]
[0.66666667 1.         0.90909091 0.90909091 1.        ]


C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 14 Results with CV accuracy of 0.7166666666666666 

[0.66666667 0.66666667 0.75       0.66666667 0.83333333]
[1.         0.83333333 0.5        0.33333333 0.83333333]
[0.6        0.625      1.         1.         0.83333333]
[0.75       0.71428571 0.66666667 0.5        0.83333333]


C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 15 Results with CV accuracy of 0.5333333333333333 

[0.58333333 0.58333333 0.5        0.54545455 0.45454545]
[0.83333333 0.83333333 0.16666667 0.4        0.83333333]
[0.55555556 0.55555556 0.5        0.5        0.5       ]
[0.66666667 0.66666667 0.25       0.44444444 0.625     ]


C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 16 Results with CV accuracy of 0.6333333333333333 

[0.5        0.75       0.5        0.66666667 0.75      ]
[0.66666667 0.66666667 0.33333333 0.33333333 0.66666667]
[0.5 0.8 0.5 1.  0.8]
[0.57142857 0.72727273 0.4        0.5        0.72727273]


C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 17 Results with CV accuracy of 0.4948717948717949 

[0.30769231 0.58333333 0.58333333 0.5        0.5       ]
[0.5        0.5        0.5        0.5        0.66666667]
[0.33333333 0.6        0.6        0.5        0.5       ]
[0.4        0.54545455 0.54545455 0.5        0.57142857]


C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 18 Results with CV accuracy of 0.5333333333333333 

[0.66666667 0.33333333 0.41666667 0.58333333 0.66666667]
[0.5        0.16666667 0.16666667 0.5        0.66666667]
[0.75       0.25       0.33333333 0.6        0.66666667]
[0.6        0.2        0.22222222 0.54545455 0.66666667]


C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 19 Results with CV accuracy of 0.8602564102564102 

[0.92307692 0.84615385 0.76923077 0.84615385 0.91666667]
[0.83333333 1.         0.85714286 1.         0.83333333]
[1.         0.77777778 0.75       0.77777778 1.        ]
[0.90909091 0.875      0.8        0.875      0.90909091]


C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 20 Results with CV accuracy of 0.5333333333333333 

[0.5        0.41666667 0.5        0.58333333 0.66666667]
[1.         0.5        0.16666667 0.5        0.5       ]
[0.5        0.42857143 0.5        0.6        0.75      ]
[0.66666667 0.46153846 0.25       0.54545455 0.6       ]


C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 21 Results with CV accuracy of 0.7166666666666668 

[0.58333333 0.5        0.83333333 0.83333333 0.83333333]
[0.83333333 0.16666667 0.66666667 0.66666667 0.83333333]
[0.55555556 0.5        1.         1.         0.83333333]
[0.66666667 0.25       0.8        0.8        0.83333333]


C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 22 Results with CV accuracy of 0.6000000000000001 

[0.83333333 0.58333333 0.75       0.25       0.58333333]
[0.83333333 0.5        0.66666667 0.16666667 0.5       ]
[0.83333333 0.6        0.8        0.2        0.6       ]
[0.83333333 0.54545455 0.72727273 0.18181818 0.54545455]


C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 23 Results with CV accuracy of 0.4833333333333334 

[0.58333333 0.41666667 0.5        0.41666667 0.5       ]
[0.83333333 0.33333333 0.5        0.33333333 0.16666667]
[0.55555556 0.4        0.5        0.4        0.5       ]
[0.66666667 0.36363636 0.5        0.36363636 0.25      ]


C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 24 Results with CV accuracy of 0.7166666666666667 

[0.58333333 0.75       0.75       0.83333333 0.66666667]
[0.66666667 0.83333333 0.66666667 0.66666667 0.83333333]
[0.57142857 0.71428571 0.8        1.         0.625     ]
[0.61538462 0.76923077 0.72727273 0.8        0.71428571]


C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 25 Results with CV accuracy of 0.4833333333333333 

[0.41666667 0.58333333 0.41666667 0.58333333 0.41666667]
[0.16666667 0.33333333 0.5        0.5        0.33333333]
[0.33333333 0.66666667 0.42857143 0.6        0.4       ]
[0.22222222 0.44444444 0.46153846 0.54545455 0.36363636]
Subject 26 Results with CV accuracy of 0.4141025641025641 

[0.15384615 0.41666667 0.5        0.5        0.5       ]
[0.33333333 0.33333333 0.66666667 0.33333333 0.33333333]
[0.22222222 0.4        0.5        0.5        0.5       ]
[0.26666667 0.36363636 0.57142857 0.4        0.4       ]


C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 27 Results with CV accuracy of 0.8666666666666668 

[0.66666667 1.         0.83333333 0.83333333 1.        ]
[0.83333333 1.         0.83333333 0.83333333 1.        ]
[0.625      1.         0.83333333 0.83333333 1.        ]
[0.71428571 1.         0.83333333 0.83333333 1.        ]


C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 28 Results with CV accuracy of 0.4 

[0.5        0.25       0.41666667 0.41666667 0.41666667]
[0.83333333 0.         0.33333333 0.5        0.5       ]
[0.5        0.         0.4        0.42857143 0.42857143]
[0.625      0.         0.36363636 0.46153846 0.46153846]


C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 29 Results with CV accuracy of 0.6666666666666666 

[0.5        0.66666667 0.75       0.91666667 0.5       ]
[0.33333333 0.66666667 0.83333333 1.         0.5       ]
[0.5        0.66666667 0.71428571 0.85714286 0.5       ]
[0.4        0.66666667 0.76923077 0.92307692 0.5       ]


C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\Seran\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-reg

Subject 30 Results with CV accuracy of 0.5089743589743589 

[0.46153846 0.5        0.66666667 0.41666667 0.5       ]
[0.5        0.5        0.66666667 0.33333333 0.66666667]
[0.42857143 0.5        0.66666667 0.4        0.5       ]
[0.46153846 0.5        0.66666667 0.36363636 0.57142857]


In [117]:
accuracy = sum(accuracy_list)/len(accuracy_list)
precision = sum(precision_list)/len(precision_list)
recall = sum(recall_list)/len(recall_list)
f1 = sum(f1_list)/len(f1_list)

In [118]:
print(f'accuracy is {accuracy}')
print(f'precision is {precision}')
print(f'recall is {recall}')
print(f'd1_score is {f1}')

accuracy is 0.6347202797202798
precision is 0.6553386243386243
recall is 0.610920634920635
d1_score is 0.6117180597180598


In [119]:
accText = 'Logistic Regression, Math vs Relax, per Subject Cross Validation'

acc = pd.read_csv("accuracies.csv", index_col=0)
acc.at[accText, 'Accuracy'] = (accuracy)
acc.at[accText, 'Precision'] = (precision)
acc.at[accText, 'Recall'] = (recall)
acc.at[accText, 'F1'] = (f1)
# acc.at[accText, 'ROC'] = (roc_auc)
acc.to_csv("accuracies.csv")

# Decision Tree

In [124]:
from sklearn.tree import DecisionTreeClassifier

In [125]:
dtree = DecisionTreeClassifier()
features = math_relax.drop(['Unnamed: 0', 'id', 'indra_time','reading_time', 'browser_latency', 'eeg_power', 'raw_values',
       'signal_quality', 'createdAt', 'updatedAt', 'Session', 'Seen video before?', 'Chosen color',
       'Saw icons?', 'Gender', 'Wear contacts','label'], axis = 1)
scaled_data = scaler.fit_transform(features)
X_train, X_test, y_train, y_test = train_test_split(features,math_relax['label'], test_size=0.30)


In [126]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [127]:
pred = dtree.predict(X_test)
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

        math       0.60      0.62      0.61       289
       relax       0.58      0.57      0.57       272

    accuracy                           0.59       561
   macro avg       0.59      0.59      0.59       561
weighted avg       0.59      0.59      0.59       561



In [128]:
print(confusion_matrix(y_test,pred))

[[178 111]
 [118 154]]


In [129]:
#calculate accuracy/precision/recall/f1

# accuracy: (tp + tn) / (p + n)
accuracy = (accuracy_score(y_test, pred)).astype('float64')
print('{:>10}: {:0.2%}'.format('Accuracy',accuracy))
# precision tp / (tp + fp)
precision = (precision_score(y_test, pred, pos_label = 'math' )).astype('float64')
print('{:>10}: {:0.2%}'.format('Precision',precision))
# recall: tp / (tp + fn)
recall = (recall_score(y_test, pred, pos_label = 'math' )).astype('float64')
print('{:>10}: {:0.2%}'.format('Recall',recall))
# f1: 2 tp / (2 tp + fp + fn)
f1 = (f1_score(y_test, pred, pos_label = 'math' )).astype('float64')
print('{:>10}: {:0.2%}'.format('F1 score',f1))

#ROC curve
# false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, pred, pos_label = 'math' )
# roc_auc = (auc(false_positive_rate, true_positive_rate)).astype('float64')
# print('{:>10}: {:0.2%}'.format('ROC score',roc_auc))

  Accuracy: 59.18%
 Precision: 60.14%
    Recall: 61.59%
  F1 score: 60.85%


In [95]:
scores = cross_val_score(dtree, scaled_data, math_relax['label'], 
                             cv = 10, scoring = 'accuracy')  
mean_score = scores.mean()
mean_score

0.6037433155080214

In [130]:
accText = 'Decision Tree'
acc = pd.read_csv("accuracies.csv", index_col=0)
acc.at[accText, 'Accuracy'] = (accuracy)
acc.at[accText, 'Precision'] = (precision)
acc.at[accText, 'Recall'] = (recall)
acc.at[accText, 'F1'] = (f1)
# acc.at[accText, 'ROC'] = (roc_auc)
acc.to_csv("accuracies.csv")

Better than logistic regression and KNN by a couple percentage points

# Decision Tree Cross Validation

In [133]:
scores = cross_val_score(dtree, scaled_data, math_relax['label'], 
                             cv = 10, scoring = 'accuracy')  
accuracy = scores.mean()
print(accuracy)

precision_scores = cross_val_score(dtree, scaled_data, math_relax_trim['label'], 
                             cv = 10, scoring = 'precision') 
precision = precision_scores.mean()
print(precision)

recall_scores = cross_val_score(dtree, scaled_data, math_relax_trim['label'], 
                             cv = 10, scoring = 'recall') 
recall = recall_scores.mean()
print(recall)

f1_scores = cross_val_score(dtree, scaled_data, math_relax_trim['label'], 
                             cv = 10, scoring = 'f1') 
f1 = f1_scores.mean()
print(f1)

0.5978609625668448
0.598434384966035
0.5959849004804394
0.5932231278431116


In [134]:
accText = 'Decision Tree, Cross Validated'
acc = pd.read_csv("accuracies.csv", index_col=0)
acc.at[accText, 'Accuracy'] = (accuracy)
acc.at[accText, 'Precision'] = (precision)
acc.at[accText, 'Recall'] = (recall)
acc.at[accText, 'F1'] = (f1)
# acc.at[accText, 'ROC'] = (roc_auc)
acc.to_csv("accuracies.csv")

# Decision Tree per Subject

In [136]:
dtree = DecisionTreeClassifier()

accuracy_list = []
recall_list = []
precision_list = []
f1_list = [] 

for i in range(1,31):
    subject = math_relax_trim[math_relax_trim['id'] == i]
    features = subject.drop(['label'], axis = 1)
    scaled_data = scaler.fit_transform(features)
    accuracy_all = cross_val_score(dtree, features, subject['label'], 
                             cv = 5, scoring = 'accuracy')
    precision_all = cross_val_score(dtree, features, subject['label'], 
                             cv = 5, scoring = 'precision') 
    recall_all = cross_val_score(dtree, features, subject['label'], 
                             cv = 5, scoring = 'recall')
    f1_all= cross_val_score(dtree, features, subject['label'], 
                             cv = 5, scoring = 'f1')
    accuracy_list.append(accuracy_all.mean())
    precision_list.append(precision_all.mean())
    recall_list.append(recall_all.mean())
    f1_list.append(f1_all.mean())
    print(f'Subject {i} Results with CV accuracy of {accuracy_all.mean()} \n')
    print(accuracy_all)
    print(recall_all)
    print(precision_all)
    print(f1_all)

Subject 1 Results with CV accuracy of 0.8166666666666668 

[0.83333333 0.83333333 0.91666667 0.83333333 0.66666667]
[1.         1.         1.         0.83333333 0.5       ]
[0.85714286 0.66666667 0.75       1.         0.75      ]
[0.92307692 0.8        0.76923077 0.90909091 0.66666667]
Subject 2 Results with CV accuracy of 0.5935897435897436 

[0.38461538 0.83333333 0.58333333 0.5        0.66666667]
[0.57142857 0.83333333 0.5        0.83333333 0.83333333]
[0.44444444 0.83333333 0.75       0.5        0.625     ]
[0.5        0.83333333 0.6        0.625      0.71428571]
Subject 3 Results with CV accuracy of 0.7772727272727272 

[0.75       0.83333333 0.91666667 0.75       0.63636364]
[0.83333333 0.83333333 1.         0.85714286 0.5       ]
[1.         0.83333333 0.875      0.75       0.8       ]
[0.61538462 0.83333333 0.93333333 0.82352941 0.72727273]
Subject 4 Results with CV accuracy of 0.4961538461538463 

[0.84615385 0.38461538 0.58333333 0.33333333 0.33333333]
[1.         0.42857143 

In [137]:
accuracy = sum(accuracy_list)/len(accuracy_list)
precision = sum(precision_list)/len(precision_list)
recall = sum(recall_list)/len(recall_list)
f1 = sum(f1_list)/len(f1_list)

In [138]:
print(f'accuracy is {accuracy}')
print(f'precision is {precision}')
print(f'recall is {recall}')
print(f'd1_score is {f1}')

accuracy is 0.6146231546231548
precision is 0.6456322751322753
recall is 0.6282857142857142
d1_score is 0.608011757305875


In [139]:
accText = 'Decision Tree, Math vs Relax, per Subject Cross Validation'

acc = pd.read_csv("accuracies.csv", index_col=0)
acc.at[accText, 'Accuracy'] = (accuracy)
acc.at[accText, 'Precision'] = (precision)
acc.at[accText, 'Recall'] = (recall)
acc.at[accText, 'F1'] = (f1)
# acc.at[accText, 'ROC'] = (roc_auc)
acc.to_csv("accuracies.csv")

# Random Forest

In [140]:
from sklearn.ensemble import RandomForestClassifier

In [141]:
rfc = RandomForestClassifier(n_estimators=600)
features = math_relax.drop(['Unnamed: 0', 'id', 'indra_time','reading_time', 'browser_latency', 'eeg_power', 'raw_values',
       'signal_quality', 'createdAt', 'updatedAt', 'Session', 'Seen video before?', 'Chosen color',
       'Saw icons?', 'Gender', 'Wear contacts','label'], axis = 1)
scaled_data = scaler.fit_transform(features)
X_train, X_test, y_train, y_test = train_test_split(features,math_relax['label'], test_size=0.30)


In [142]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=600,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [143]:
pred = rfc.predict(X_test)

In [145]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

        math       0.69      0.67      0.68       292
       relax       0.65      0.67      0.66       269

    accuracy                           0.67       561
   macro avg       0.67      0.67      0.67       561
weighted avg       0.67      0.67      0.67       561



In [146]:
print(confusion_matrix(y_test,predictions))

[[ 96 196]
 [ 75 194]]


In [147]:
#calculate accuracy/precision/recall/f1

# accuracy: (tp + tn) / (p + n)
accuracy = (accuracy_score(y_test, pred)).astype('float64')
print('{:>10}: {:0.2%}'.format('Accuracy',accuracy))
# precision tp / (tp + fp)
precision = (precision_score(y_test, pred, pos_label = 'math' )).astype('float64')
print('{:>10}: {:0.2%}'.format('Precision',precision))
# recall: tp / (tp + fn)
recall = (recall_score(y_test, pred, pos_label = 'math' )).astype('float64')
print('{:>10}: {:0.2%}'.format('Recall',recall))
# f1: 2 tp / (2 tp + fp + fn)
f1 = (f1_score(y_test, pred, pos_label = 'math' )).astype('float64')
print('{:>10}: {:0.2%}'.format('F1 score',f1))

#ROC curve
# false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, pred, pos_label = 'math' )
# roc_auc = (auc(false_positive_rate, true_positive_rate)).astype('float64')
# print('{:>10}: {:0.2%}'.format('ROC score',roc_auc))

  Accuracy: 67.20%
 Precision: 68.88%
    Recall: 67.47%
  F1 score: 68.17%


In [148]:
accText = 'Random Forest'
acc = pd.read_csv("accuracies.csv", index_col=0)
acc.at[accText, 'Accuracy'] = (accuracy)
acc.at[accText, 'Precision'] = (precision)
acc.at[accText, 'Recall'] = (recall)
acc.at[accText, 'F1'] = (f1)
# acc.at[accText, 'ROC'] = (roc_auc)
acc.to_csv("accuracies.csv")

# Random Forest Cross Validation

In [149]:
scores = cross_val_score(rfc, scaled_data, math_relax['label'], 
                             cv = 10, scoring = 'accuracy')  
accuracy = scores.mean()
print(accuracy)

precision_scores = cross_val_score(rfc, scaled_data, math_relax_trim['label'], 
                             cv = 10, scoring = 'precision') 
precision = precision_scores.mean()
print(precision)

recall_scores = cross_val_score(rfc, scaled_data, math_relax_trim['label'], 
                             cv = 10, scoring = 'recall') 
recall = recall_scores.mean()
print(recall)

f1_scores = cross_val_score(rfc, scaled_data, math_relax_trim['label'], 
                             cv = 10, scoring = 'f1') 
f1 = f1_scores.mean()
print(f1)

0.6304812834224599
0.6396381389238082
0.617387325554793
0.6274276863014332


In [150]:
accText = 'Random Forest, Cross Validated'
acc = pd.read_csv("accuracies.csv", index_col=0)
acc.at[accText, 'Accuracy'] = (accuracy)
acc.at[accText, 'Precision'] = (precision)
acc.at[accText, 'Recall'] = (recall)
acc.at[accText, 'F1'] = (f1)
# acc.at[accText, 'ROC'] = (roc_auc)
acc.to_csv("accuracies.csv")

# Random Forest Per Subject

In [151]:
rfc = RandomForestClassifier(n_estimators=200)
# features = math_relax.drop(['Unnamed: 0', 'id', 'indra_time','reading_time', 'browser_latency', 'eeg_power', 'raw_values',
#        'signal_quality', 'createdAt', 'updatedAt', 'Session', 'Seen video before?', 'Chosen color',
#        'Saw icons?', 'Gender', 'Wear contacts','label'], axis = 1)
# scaled_data = scaler.fit_transform(features)
accuracy_list = []

for i in range(1,31):
    subject = math_relax_trim[math_relax_trim['id'] == i]
    features = subject.drop(['label'], axis = 1)
    scaled_data = scaler.fit_transform(features)
    accuracy_all = cross_val_score(rfc, features, subject['label'], 
                             cv = 5, scoring = 'accuracy')
    precision_all = cross_val_score(rfc, features, subject['label'], 
                             cv = 5, scoring = 'precision') 
    recall_all = cross_val_score(rfc, features, subject['label'], 
                             cv = 5, scoring = 'recall')
    f1_all= cross_val_score(rfc, features, subject['label'], 
                             cv = 5, scoring = 'f1')
    accuracy_list.append(accuracy_all.mean())
    precision_list.append(precision_all.mean())
    recall_list.append(recall_all.mean())
    f1_list.append(f1_all.mean())
    print(f'Subject {i} Results with CV accuracy of {accuracy_all.mean()} \n')
    print(accuracy_all)
    print(recall_all)
    print(precision_all)
    print(f1_all)

Subject 1 Results with CV accuracy of 0.85 

[0.91666667 0.83333333 0.91666667 1.         0.58333333]
[0.83333333 1.         1.         1.         0.5       ]
[0.85714286 0.66666667 0.85714286 1.         0.66666667]
[0.83333333 0.8        0.92307692 1.         0.6       ]
Subject 2 Results with CV accuracy of 0.5948717948717949 

[0.30769231 0.75       0.66666667 0.58333333 0.66666667]
[0.42857143 0.16666667 0.5        0.66666667 0.83333333]
[0.375      0.8        0.6        0.57142857 0.625     ]
[0.42857143 0.72727273 0.6        0.61538462 0.71428571]
Subject 3 Results with CV accuracy of 0.8621212121212121 

[0.91666667 0.83333333 1.         0.83333333 0.72727273]
[0.83333333 1.         1.         1.         0.66666667]
[1.         0.83333333 1.         0.77777778 0.8       ]
[0.90909091 0.92307692 1.         0.875      0.72727273]
Subject 4 Results with CV accuracy of 0.608974358974359 

[0.84615385 0.61538462 0.58333333 0.5        0.5       ]
[0.83333333 0.57142857 0.5        0.66

In [152]:
accuracy = sum(accuracy_list)/len(accuracy_list)
precision = sum(precision_list)/len(precision_list)
recall = sum(recall_list)/len(recall_list)
f1 = sum(f1_list)/len(f1_list)

In [153]:
print(f'accuracy is {accuracy}')
print(f'precision is {precision}')
print(f'recall is {recall}')
print(f'd1_score is {f1}')

accuracy is 0.6616899766899768
precision is 0.6619369889369892
recall is 0.6517777777777777
d1_score is 0.630341162105868


In [154]:
accText = 'Random Forest, Math vs Relax, per Subject Cross Validation'

acc = pd.read_csv("accuracies.csv", index_col=0)
acc.at[accText, 'Accuracy'] = (accuracy)
acc.at[accText, 'Precision'] = (precision)
acc.at[accText, 'Recall'] = (recall)
acc.at[accText, 'F1'] = (f1)
# acc.at[accText, 'ROC'] = (roc_auc)
acc.to_csv("accuracies.csv")